# Generated by Django 5.2 on 2025-04-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "isbn_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("author_name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("published_year", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.IntegerField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("no_of_students", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Companies",
            fields=[
                ("company_id", models.IntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("industry_type", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=50)),
                ("contact_phone", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Culture",
            fields=[
                ("culture_id", models.IntegerField(primary_key=True, serialize=False)),
                ("club_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gymkhana",
            fields=[
                ("gymkhana_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("prof_id", models.IntegerField(primary_key=True, serialize=False)),
                ("prof_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("email_id", models.EmailField(max_length=100)),
                ("date_of_joining", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPrograms",
            fields=[
                ("program_id", models.IntegerField(primary_key=True, serialize=False)),
                ("program_name", models.CharField(max_length=100)),
                ("organized_by", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
            },
        ),
        migrations.CreateModel(
            name="CultureEvents",
            fields=[
                ("event_id", models.IntegerField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dbms_app.culture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Culture Event",
                "verbose_name_plural": "Culture Events",
            },
        ),
        migrations.CreateModel(
            name="GymkhanaEvents",
            fields=[
                ("event_id", models.IntegerField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                (
                    "gymkhana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dbms_app.gymkhana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gymkhana Event",
                "verbose_name_plural": "Gymkhana Events",
            },
        ),
        migrations.CreateModel(
            name="ManagementPhone",
            fields=[
                ("phone_no_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_no", models.CharField(max_length=15)),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="dbms_app.management",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                ("library_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("seating_capacity", models.IntegerField()),
                (
                    "librarian",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libraries_managed",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                ("hostel_id", models.IntegerField(primary_key=True, serialize=False)),
                ("hostel_name", models.CharField(max_length=50)),
                ("no_of_beds", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                (
                    "warden",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostels_managed",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gymkhana",
            name="president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gymkhana_president",
                to="dbms_app.professor",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("no_of_programs", models.IntegerField()),
                (
                    "hod",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_headed",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("batch_id", models.IntegerField(primary_key=True, serialize=False)),
                ("batch_name", models.CharField(max_length=50)),
                (
                    "class_field",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="dbms_app.class",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentored_batches",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AntiRaggingCommittee",
            fields=[
                (
                    "committee_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "head_professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_committees",
                        to="dbms_app.professor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anti-Ragging Committees",
            },
        ),
        migrations.CreateModel(
            name="ProfessorPhone",
            fields=[
                ("phone_no_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_no", models.CharField(max_length=15)),
                (
                    "prof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("program_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("no_of_courses", models.IntegerField()),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dept_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="dbms_app.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sports",
            fields=[
                ("sport_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sport_name", models.CharField(max_length=50, unique=True)),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sports_coached",
                        to="dbms_app.professor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sports",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "class_field",
                    models.ForeignKey(
                        db_column="class_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="dbms_app.class",
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="dbms_app.hostel",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="dbms_app.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordBook",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("issued_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "late_fine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "isbn_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dbms_app.books",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_records",
                        to="dbms_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOffers",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_role", models.CharField(max_length=100)),
                ("package", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_offers",
                        to="dbms_app.companies",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_offers",
                        to="dbms_app.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Offer",
                "verbose_name_plural": "Job Offers",
            },
        ),
        migrations.CreateModel(
            name="Internships",
            fields=[
                ("internship_id", models.AutoField(primary_key=True, serialize=False)),
                ("internship_role", models.CharField(max_length=100)),
                (
                    "stipend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("duration_months", models.IntegerField()),
                ("internship_start_date", models.DateField()),
                ("internship_end_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="dbms_app.companies",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="dbms_app.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Internships",
            },
        ),
        migrations.AddField(
            model_name="gymkhana",
            name="secretary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gymkhana_secretary",
                to="dbms_app.student",
            ),
        ),
        migrations.AddField(
            model_name="gymkhana",
            name="vice_president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gymkhana_vice_president",
                to="dbms_app.student",
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="club_president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_president",
                to="dbms_app.student",
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="club_vice_president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_vice_president",
                to="dbms_app.student",
            ),
        ),
        migrations.CreateModel(
            name="Complaints",
            fields=[
                ("complaint_id", models.AutoField(primary_key=True, serialize=False)),
                ("complaint_details", models.TextField()),
                ("complaint_date", models.DateField()),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Resolved", "Resolved"),
                            ("Dismissed", "Dismissed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="dbms_app.antiraggingcommittee",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="dbms_app.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaints",
            },
        ),
        migrations.AddField(
            model_name="antiraggingcommittee",
            name="student_representative",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="represented_committees",
                to="dbms_app.student",
            ),
        ),
        migrations.CreateModel(
            name="TeachingAssistant",
            fields=[
                ("ta_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ta_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("email_id", models.EmailField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_joining", models.DateField()),
                (
                    "prof",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_assistants",
                        to="dbms_app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                ("lab_id", models.IntegerField(primary_key=True, serialize=False)),
                ("lab_name", models.CharField(max_length=50)),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labs_instructed",
                        to="dbms_app.professor",
                    ),
                ),
                (
                    "lab_assistant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labs_assisted",
                        to="dbms_app.teachingassistant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingAssistantPhone",
            fields=[
                ("phone_no_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_no", models.CharField(max_length=15)),
                (
                    "ta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="dbms_app.teachingassistant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlacementCell",
            fields=[
                ("tpc_id", models.IntegerField(primary_key=True, serialize=False)),
                ("office_location", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=50, unique=True)),
                ("contact_phone", models.CharField(max_length=15, unique=True)),
                (
                    "head_professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_tpc",
                        to="dbms_app.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training & Placement Cell",
                "verbose_name_plural": "Training & Placement Cells",
            },
        ),
        migrations.CreateModel(
            name="StudentSports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms_app.sports",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms_app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "sport")},
            },
        ),
        migrations.CreateModel(
            name="StudentTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Ongoing", "Ongoing"),
                            ("Not Completed", "Not Completed"),
                        ],
                        max_length=15,
                    ),
                ),
                ("certificate_issued", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms_app.student",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms_app.trainingprograms",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "program")},
            },
        ),
    ]
