# Generated by Django 5.2 on 2025-04-08 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbms_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEntityPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Management", "Management"),
                            ("ManagementPhone", "ManagementPhone"),
                            ("Professor", "Professor"),
                            ("ProfessorPhone", "ProfessorPhone"),
                            ("Department", "Department"),
                            ("Program", "Program"),
                            ("Class", "Class"),
                            ("Hostel", "Hostel"),
                            ("Student", "Student"),
                            ("TeachingAssistant", "TeachingAssistant"),
                            ("TeachingAssistantPhone", "TeachingAssistantPhone"),
                            ("Batch", "Batch"),
                            ("Lab", "Lab"),
                            ("Library", "Library"),
                            ("Books", "Books"),
                            ("RecordBook", "RecordBook"),
                            ("Sports", "Sports"),
                            ("StudentSports", "StudentSports"),
                            ("Gymkhana", "Gymkhana"),
                            ("GymkhanaEvents", "GymkhanaEvents"),
                            ("Culture", "Culture"),
                            ("CultureEvents", "CultureEvents"),
                            ("AntiRaggingCommittee", "AntiRaggingCommittee"),
                            ("Complaints", "Complaints"),
                            ("TrainingPlacementCell", "TrainingPlacementCell"),
                            ("Companies", "Companies"),
                            ("JobOffers", "JobOffers"),
                            ("Internships", "Internships"),
                            ("TrainingPrograms", "TrainingPrograms"),
                            ("StudentTraining", "StudentTraining"),
                        ],
                        max_length=100,
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "entity_type")},
            },
        ),
    ]
